### ISSUE TITLE
Works with VMware vSphere, between Ubuntu 20.04 servers?

### ISSUE THREAD

**Issue by komaromibandi** [juju4/ansible-MISP#12]
Hi, I have tried many times to install from an Ubuntu server to an other Ubuntu server, but the playbook always failed or I could not reach the starting screen from the browser. I have checkd many things, but I dont know what more I can do. So if anyone know this role works with VMware vSphere client, with ubuntu server 20.04, or centos 8?

**Comment by juju4** [comment]
Please provide more information on your context
- Target distribution: ubuntu 20.04 or centos 8
- Underlying infra: vmware - should not really matter
- what version or commit of this role are you using?
- default or custom settings?
- what command are you using? what error message do you get?

Note that this role has github actions configure with regular execution to validate
https://github.com/juju4/ansible-MISP/actions
there is currently a config issue with composer that is fixed in devel in my own manual testing but for some reasons, still failing in github actions.
You can eventually try it if feel comfortable.

**Comment by komaromibandi** [comment]
Sorry for the late answer, I had a lot of work. Here are the required informations:

  - I use Ubuntu 20.04.4 LTS, in both side
  - I use juju4.MISP (1.3.1) version, with the newest ansible version (2.9.6+dfsg-1)
  - I have successfull ssh connection between the instances
  - In the .yml file I have this code:
    
![image](https://user-images.githubusercontent.com/78871051/185793587-eb2a15ce-e8a9-4654-83a7-f79035b0a94a.png)

  - The [vm116] line has the following configuration:
    `[vm116]
10.35.116.116 ansible_ssh_pass=password ansible_ssh_user=root`

- To start I use the command: `ansible-playbook misp.yml` 
- I attach a txt which contains the output of the script.
[output.txt](https://github.com/juju4/ansible-MISP/files/9389318/output.txt)

Thanks in advance!

**Comment by juju4** [comment]
Thanks.
Please try with roles from master HEAD. You can retrieve it with a `git clone`. A new tag should come soon as I usually try to do twice a year.
For ansible, should be fine but not newest/latest as 6.2.0 from https://pypi.org/project/ansible/#history. You have latest from ubuntu system repo.

it fails on "setting core.filemode for git". You can
- edit task file and add missing become/become_user as can be seen when checking 1.3.1 and master.
https://github.com/juju4/ansible-MISP/blob/1.3.1/tasks/main.yml#L236
https://github.com/juju4/ansible-MISP/blob/master/tasks/main.yml#L239
- run `ansible -v misp.yml` to increase verbosity (up to 4x v)

**Comment by komaromibandi** [comment]
Sorry to not answer, I was delegated to an other task on my workplace. I tryed all the suggestions and still does not working. output file:
[out2.txt](https://github.com/juju4/ansible-MISP/files/9939904/out2.txt)

I installed manually the newest ansible, the 6.5.0, but the Ubuntu did not like it. So I stayed at the ansible [core 2.13.6rc1] version.

I checked the main.yml file and I saw there was update, so the suggested lines were there.
![image](https://user-images.githubusercontent.com/78871051/200021599-9a8ceceb-c606-4d30-bf67-1506dd2f0272.png)

I started the yml file with the following command (I choosed an other name to the yml file this time):
`ansible-playbook -v yes.yml > out2.txt`
I copied the yes.yml into the  ansible-MISP/   library
![image](https://user-images.githubusercontent.com/78871051/200022534-096c66c4-fce9-4136-b0dd-1fd899cad3e3.png)


Do you have any ideas what could I do?

**Comment by juju4** [comment]
It is still failing on same task
```
TASK [juju4.MISP : setting core.filemode for git] ******************************
fatal: [10.35.116.116]: FAILED! => {"changed": false, "cmd": "/usr/bin/git config --includes --local core.filemode", "msg": "fatal: --local can only be used inside a git repository\n", "rc": 128}
```

can you try to do the command manually, disable this ansible task and rerun the play?
```
cd /var/www/_MISP/MISP
git config --includes --local core.filemode
```
you can disable the task by adding a `when: false`.

I tried manual run on 20.04 too and this task is not failing for me.

**Comment by komaromibandi** [comment]
First, I would like to thank for your help, I really appreciate it. I wanted to react sooner, but presumably my virtual machines are cursed, or whatever. When I find a solution something, even the earlier tihings, goes wrong, just like this time. I got this error messege:

[output.txt](https://github.com/juju4/ansible-MISP/files/10050793/output.txt)

Earlier somehow I fixed it (improvised and tried a lot), but I did not know this time why it is always failing.

Secondly, I suspect where I made mistakes in connection with the previous questions, so maybe after this problem it will work.

Thirdly, I can record a short timelapse video with obs and send you, what I am doing, if its help you.

**Comment by juju4** [comment]
What is current status for this?

in your output.txt, there is
```
TASK [juju4.MISP : apt | MISP dependencies install] ****************************
ASYNC FAILED on 10.35.116.114: jid=325525718794.1810
FAILED - RETRYING: [10.35.116.114]: apt | MISP dependencies install (3 retries left).
ASYNC FAILED on 10.35.116.114: jid=706302355937.3288
FAILED - RETRYING: [10.35.116.114]: apt | MISP dependencies install (2 retries left).
ASYNC FAILED on 10.35.116.114: jid=265351132502.3774
FAILED - RETRYING: [10.35.116.114]: apt | MISP dependencies install (1 retries left).
ASYNC FAILED on 10.35.116.114: jid=209794237974.4233
fatal: [10.35.116.114]: FAILED! => {"ansible_job_id": "209794237974.4233", "attempts": 3, "changed": false, "finished": 1, "msg": "Failed to lock apt for exclusive operation: Failed to lock directory /var/lib/apt/lists/: E:Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)", "results_file": "/home/andrew/.ansible_async/209794237974.4233", "started": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

the apt package task is failing, most likely because already an ongoing apt tasks for background updates probably.
retrying few minutes later or checking if any apt process is still active should be fine.

**Comment by juju4** [comment]
Closing as no update.
Reopen if needed.
